algoritmo "exercicio10"
// Função :
// Autor :
// Data : 16/08/2020
// Seção de Declarações 
var
altura, largura, area, tinta: Real
inicio
// Seção de Comandos 
Escreva("Informe a altura da parede: ")
Leia(altura)
Escreva("Informe a largura da parede: ")
Leia(largura)
area <- largura * altura
tinta <- area/2
Escreva("A área a ser se pintada é de", area, " metros quadrados e necessite de", tinta, "L de tinta para ser pintada.")
fimalgoritmo
