algoritmo "semnome"
// Função :
// Autor :
// Data : 15/08/2020
// Seção de Declarações 
var
 distancia: Real
inicio
// Seção de Comandos 
 Escreva("Digite a distância em metros: ")
 Leia(distancia)
 Escreval("A distância de", distancia, "m corresponde a:")
 Escreval(distancia/1000)
 Escreval(distancia/100)
 Escreval(distancia/10)
 Escreval(distancia*10)
 Escreval(distancia*100)
 Escreval(distancia*1000)
fimalgoritmo
