algoritmo "exercicio_idade_aula6"
// Função :
// Autor :
// Data : 16/08/2020
// Seção de Declarações 
var
   ano_atual, ano_nasci, idade: Inteiro
inicio
// Seção de Comandos 
         Escreva("Em que ano estamos?")
         Leia(ano_atual)
         Escreva("Em que ano nasci?")
         Leia(ano_nasci)
         idade <- ano_atual - ano_nasci
         Escreva("Minha idade será", idade)
fimalgoritmo
